apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: demo-services
spec:
  interval: 5m
  provider: azure
  url: oci://acragenticbasedev001mjil.azurecr.io/helm/resiliency-app
  ref:
    digest: sha256:04ebd77f2801b778ab77c708f61386500b5625a808aab14a5d5fb1a41aba042d
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
