apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: demo-services
spec:
  interval: 5m
  provider: azure
  url: oci://acragenticbasedev001mjil.azurecr.io/helm/resiliency-app
  ref:
    digest: sha256:2d06919a4e1663ae1e8c1c8fb1db510068bc9bddb9ce454a2a4f32d78103ada8
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
