apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: demo-services
spec:
  interval: 5m
  provider: azure
  url: oci://acragenticbasedev001pq4u.azurecr.io/helm/resiliency-app
  ref:
    digest: sha256:612a345efbfe7ed1a4448a2935fe60c9290b2a1d1c95be6d6fd2ac2f72e48197
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
