apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: "resiliency-app-ux-redis-chart"
  namespace: "demo-services"
spec:
  interval: 5m
  provider: azure
  url: "oci://acrmrv2uxdevwus2001.azurecr.io/helm/resiliency-app-ux-redis"
  ref:
    digest: "sha256:bb3bbd96d44545b071ca37aebc8968dce937b69ec871a2e602c5e26d36685840"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
