apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: "resiliency-app-ux-redis-chart"
  namespace: "demo-services"
spec:
  interval: 5m
  provider: azure
  url: "oci://acrmrv2uxdevwus2001.azurecr.io/helm/resiliency-app-ux-redis"
  ref:
    digest: "sha256:087c59e61cdcd52281d365985ff89e48814267aec149d8c8fdbea97bed20715e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
