apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: aks-istio-ingress
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "0e01d70e-d4cc-45b7-9f66-17054bea64fd"
    keyvaultName: "kvprovenirchklistdev001"
    cloudName: "AzurePublicCloud"
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
    objects:  |
      array:
        - |
          objectName: "istio-tls-crt"
          objectType: secret
        - |
          objectName: "istio-tls-key"
          objectType: secret
  secretObjects:
    - secretName: istio-ingress-tls
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: "istio-tls-crt"
        - key: tls.key
          objectName: "istio-tls-key"