apiVersion: v1
kind: ConfigMap
metadata:
  name: ${UX_CONFIG_MAP_NAME}
  namespace: ${UX_APP_NAMESPACE}
data:
  SPRING_PROFILES_ACTIVE: "${UX_SPRING_PROFILE}"
  BACKEND_EMPLOYEES_BASE_URL: "${UX_BACKEND_BASE_URL}"
  BACKEND_EMPLOYEES_HEALTH_ENABLED: "${UX_BACKEND_HEALTH_ENABLED}"
  BACKEND_EMPLOYEES_HEALTH_URL: "${UX_BACKEND_HEALTH_URL}"
