apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${UX_APP_NAME}
  namespace: ${UX_APP_NAMESPACE}
spec:
  replicas: ${UX_REPLICAS}
  selector:
    matchLabels:
      app: ${UX_APP_NAME}
  template:
    metadata:
      labels:
        app: ${UX_APP_NAME}
        sidecar.istio.io/inject: "${UX_SIDECAR_INJECT}"
      annotations:
        proxy.istio.io/config: "${UX_SIDECAR_PROXY_CONFIG}"
    spec:
      serviceAccountName: ${UX_SERVICE_ACCOUNT_NAME}
      containers:
      - name: ${UX_CONTAINER_NAME}
        image: ${UX_IMAGE}
        imagePullPolicy: ${UX_IMAGE_PULL_POLICY}
        envFrom:
        - configMapRef:
            name: ${UX_CONFIG_MAP_NAME}
        resources:
          requests:
            cpu: "${UX_RESOURCES_REQUESTS_CPU}"
            memory: "${UX_RESOURCES_REQUESTS_MEMORY}"
          limits:
            cpu: "${UX_RESOURCES_LIMITS_CPU}"
            memory: "${UX_RESOURCES_LIMITS_MEMORY}"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 100
          runAsGroup: 101
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        ports:
        - name: ${UX_SERVICE_PORT_NAME}
          containerPort: ${UX_CONTAINER_PORT}
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
