apiVersion: apps/v1
kind: Deployment
metadata:
  name: ux-client
  namespace: ux-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ux-client
  template:
    metadata:
      labels:
        app: ux-client
        sidecar.istio.io/inject: 'true'
      annotations:
        proxy.istio.io/config: 'holdApplicationUntilProxyStarts: true'
    spec:
      serviceAccountName: ux-client
      containers:
      - name: client
        image: dummy:1.0.0
        envFrom:
        - configMapRef:
            name: ux-client-settings
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        ports:
        - name: http
          containerPort: 8080
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
