apiVersion: v1
kind: Service
metadata:
  name: ${UX_APP_NAME}
  namespace: ${UX_APP_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: ${UX_APP_NAME}
  ports:
  - name: ${UX_SERVICE_PORT_NAME}
    port: ${UX_SERVICE_PORT}
    targetPort: ${UX_SERVICE_PORT_NAME}
