channel: validation
flow: redis-multiregion
domain: resiliency
capability: redis
appName: resiliency-app-redis
appProfile: aks
replicaCount: 2
image:
  repository: acragenticbasedev001pq4u.azurecr.io/apps/redis
  digest: sha256:5377d45871763dba0808dfa432c3c1519e9354cca98ec46470de793ebdef7b12
nodeSelector:
  kubernetes.azure.com/agentpool: workload
  topology.credicorp.com/region: westus3
redis:
  hostname: redis-mr-dev-westus3-001.westus3.redis.azure.net
  port: 10000
  tls: true
  scope: https://redis.azure.com/.default
  username: 4dbea156-f605-4172-b0ca-3e7b14355921
workloadIdentity:
  clientId: 56a7f705-9736-4187-8659-6579c3db4d7a
  principalId: 4dbea156-f605-4172-b0ca-3e7b14355921
  tenantId: 00dc56d8-1058-405b-bc47-03af055246cb
  issuer: https://westus3.oic.prod-aks.azure.com/00dc56d8-1058-405b-bc47-03af055246cb/3cc9da02-c0ea-4496-9834-42186184d274/
  subject: system:serviceaccount:demo-services:demo-services
  audience: api://AzureADTokenExchange
serviceAccount:
  name: demo-services
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
istio:
  gateway:
    name: istio-ingress-gateway-internal
    namespace: aks-istio-ingress
  virtualService:
    hosts:
      - demo-services.internal.cloudcompany.pe
    path: /api/employees
    readinessPath: /actuator/health/readiness
