apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ${UX_APIM_RESOURCE_NAME}
  namespace: ${UX_APP_NAMESPACE}
spec:
  hosts:
  - ${UX_APIM_LOGICAL_HOST}
  gateways:
  - mesh
  exportTo:
  - .
  http:
  - name: safe-methods
    match:
    - method:
        regex: ${UX_SAFE_METHODS_REGEX}
    timeout: ${UX_SAFE_TIMEOUT}
    retries:
      attempts: ${UX_SAFE_RETRY_ATTEMPTS}
      perTryTimeout: ${UX_SAFE_PER_TRY_TIMEOUT}
      retryOn: ${UX_SAFE_RETRY_ON}
      retryRemoteLocalities: ${UX_SAFE_RETRY_REMOTE_LOCALITIES}
      retryIgnorePreviousHosts: ${UX_SAFE_RETRY_IGNORE_PREVIOUS_HOSTS}
      backoff: ${UX_SAFE_BACKOFF}
    rewrite:
      uriRegexRewrite:
        match: "^/api/employees(.*)$"
        rewrite: "/resiliency-app-redis/api/employees\\1"
    route:
    - destination:
        host: ${UX_APIM_LOGICAL_HOST}
        port:
          number: ${UX_APIM_SERVICE_PORT}
      weight: 100
  - name: mutating-methods
    match:
    - method:
        regex: ${UX_MUTATING_METHODS_REGEX}
    timeout: ${UX_MUTATING_TIMEOUT}
    retries:
      attempts: ${UX_MUTATING_RETRY_ATTEMPTS}
    rewrite:
      uriRegexRewrite:
        match: "^/api/employees(.*)$"
        rewrite: "/resiliency-app-redis/api/employees\\1"
    route:
    - destination:
        host: ${UX_APIM_LOGICAL_HOST}
        port:
          number: ${UX_APIM_SERVICE_PORT}
      weight: 100
  - name: other-methods
    timeout: ${UX_OTHER_TIMEOUT}
    retries:
      attempts: ${UX_OTHER_RETRY_ATTEMPTS}
    rewrite:
      uriRegexRewrite:
        match: "^/api/employees(.*)$"
        rewrite: "/resiliency-app-redis/api/employees\\1"
    route:
    - destination:
        host: ${UX_APIM_LOGICAL_HOST}
        port:
          number: ${UX_APIM_SERVICE_PORT}
      weight: 100