apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingress-gateway-internal
  namespace: aks-istio-ingress
  labels:
    app: istio-ingress-gateway
spec:
  selector:
    istio: aks-istio-ingressgateway-internal
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: istio-ingress-tls
      hosts:
        - azingress.porvenir.int